version: '3.1'
services:
  dotnet:
    build:
      context: ./backend
      dockerfile: ./dockerfile
      args:
        - PROJECT_PORT=5000
    container_name: 'store-dotnet'
    restart: on-failure
    ports:
        - "5000:5000"
    networks:
        - back
    environment:
        ASPNETCORE_ENVIRONMENT: 'Production'

  frontend:
    depends_on:
        - dotnet
    build:
        context: ./frontend
        dockerfile: Dockerfile
    container_name: 'frontend'
    restart: on-failure
    ports:
        - "4200:80"
    networks:
        - back
        - front

networks:
    back:
        driver: bridge
    front:
        driver: bridge